# Generated by Django 4.2.7 on 2025-12-15 05:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDisaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disaster_type', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('occurrence_date', models.DateField()),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('casualties', models.IntegerField(default=0)),
                ('damage_usd', models.BigIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Historical Disasters',
                'ordering': ['-occurrence_date'],
            },
        ),
        migrations.CreateModel(
            name='RiskModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('disaster_type', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField()),
                ('weights', models.JSONField()),
                ('thresholds', models.JSONField()),
                ('is_active', models.BooleanField(default=False)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisasterEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disaster_type', models.CharField(choices=[('flood', 'Flood'), ('earthquake', 'Earthquake'), ('cyclone', 'Cyclone'), ('wildfire', 'Wildfire')], max_length=50)),
                ('status', models.CharField(choices=[('predicted', 'Predicted'), ('active', 'Active'), ('contained', 'Contained'), ('resolved', 'Resolved')], default='predicted', max_length=50)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('location_name', models.CharField(max_length=255)),
                ('risk_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confidence_level', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('wind_speed_kmh', models.FloatField(blank=True, null=True)),
                ('rainfall_mm', models.FloatField(blank=True, null=True)),
                ('affected_area_sqkm', models.FloatField(blank=True, null=True)),
                ('predicted_time', models.DateTimeField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_affected_population', models.IntegerField(default=0)),
                ('estimated_damage_usd', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-predicted_time'],
                'indexes': [models.Index(fields=['disaster_type', 'status'], name='disasters_d_disaste_35ddb4_idx'), models.Index(fields=['risk_score'], name='disasters_d_risk_sc_606fd4_idx'), models.Index(fields=['predicted_time'], name='disasters_d_predict_fb4fa1_idx')],
            },
        ),
        migrations.CreateModel(
            name='DisasterData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_type', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('metadata', models.JSONField(default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='disasters.disasterevent')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event', 'timestamp'], name='disasters_d_event_i_accb41_idx')],
            },
        ),
    ]
