# Generated by Django 4.2.7 on 2025-12-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='endpoint',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('api', 'API'), ('csv', 'CSV Upload'), ('file', 'File Upload'), ('database', 'Database'), ('sensor', 'Sensor Network'), ('satellite', 'Satellite Data'), ('weather', 'Weather Service'), ('stream', 'Data Stream')], max_length=50),
        ),
    ]
