# Generated by Django 4.2.7 on 2025-12-15 05:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_alerts', models.IntegerField(default=0)),
                ('critical_alerts', models.IntegerField(default=0)),
                ('high_alerts', models.IntegerField(default=0)),
                ('medium_alerts', models.IntegerField(default=0)),
                ('low_alerts', models.IntegerField(default=0)),
                ('avg_response_time_minutes', models.FloatField(default=0)),
                ('acknowledgment_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DisasterAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disaster_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('total_events', models.IntegerField(default=0)),
                ('high_risk_events', models.IntegerField(default=0)),
                ('avg_risk_score', models.FloatField(default=0)),
                ('total_affected_population', models.IntegerField(default=0)),
                ('total_estimated_damage', models.BigIntegerField(default=0)),
                ('affected_regions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('api_response_time_ms', models.FloatField(default=0)),
                ('database_query_time_ms', models.FloatField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_events_processed', models.IntegerField(default=0)),
                ('alerts_generated', models.IntegerField(default=0)),
                ('cpu_usage_percent', models.FloatField(default=0)),
                ('memory_usage_percent', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
