# Generated by Django 4.2.7 on 2025-12-15 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='disasteranalytics',
            index=models.Index(fields=['disaster_type', 'date'], name='analytics_d_disaste_634f65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='disasteranalytics',
            unique_together={('disaster_type', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='alertanalytics',
            unique_together={('date',)},
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_u_user_id_9f6b02_idx'),
        ),
    ]
